/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Daniela Garcia Rios
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Jl_nombre = new javax.swing.JLabel();
        Jl_email = new javax.swing.JLabel();
        Jtf_nombre_agenda = new javax.swing.JTextField();
        Jtf_email_agenda = new javax.swing.JTextField();
        Jb_primero = new javax.swing.JButton();
        Jb_anterior = new javax.swing.JButton();
        Jb_siguiente = new javax.swing.JButton();
        Jb_ultimo = new javax.swing.JButton();
        jb_nuevo_registro = new javax.swing.JButton();
        jb_insertar_registro = new javax.swing.JButton();
        jb_modificar_registro = new javax.swing.JButton();
        Jb_eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        Jl_nombre.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        Jl_nombre.setText("Nombre");

        Jl_email.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        Jl_email.setText("Email");

        Jb_primero.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        Jb_primero.setText("|<");

        Jb_anterior.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        Jb_anterior.setText("<<");

        Jb_siguiente.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        Jb_siguiente.setText(">>");

        Jb_ultimo.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        Jb_ultimo.setText(">|");

        jb_nuevo_registro.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jb_nuevo_registro.setText("Nuevo");

        jb_insertar_registro.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jb_insertar_registro.setText("Insertar");
        jb_insertar_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_insertar_registroActionPerformed(evt);
            }
        });

        jb_modificar_registro.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jb_modificar_registro.setText("Modificar");

        Jb_eliminar.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        Jb_eliminar.setText("Eliminar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jl_nombre)
                            .addComponent(Jl_email))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jtf_nombre_agenda, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(Jtf_email_agenda)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jb_primero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jb_anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jb_siguiente)
                        .addGap(18, 18, 18)
                        .addComponent(Jb_ultimo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_nuevo_registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_modificar_registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_insertar_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jl_nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Jtf_nombre_agenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jl_email)
                    .addComponent(Jtf_email_agenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_nuevo_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_insertar_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_modificar_registro)
                    .addComponent(Jb_eliminar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jb_primero)
                    .addComponent(Jb_anterior)
                    .addComponent(Jb_siguiente)
                    .addComponent(Jb_ultimo))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_insertar_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_insertar_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_insertar_registroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Jb_anterior;
    public javax.swing.JButton Jb_eliminar;
    public javax.swing.JButton Jb_primero;
    public javax.swing.JButton Jb_siguiente;
    public javax.swing.JButton Jb_ultimo;
    public javax.swing.JLabel Jl_email;
    public javax.swing.JLabel Jl_nombre;
    public javax.swing.JTextField Jtf_email_agenda;
    public javax.swing.JTextField Jtf_nombre_agenda;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jb_insertar_registro;
    public javax.swing.JButton jb_modificar_registro;
    public javax.swing.JButton jb_nuevo_registro;
    // End of variables declaration//GEN-END:variables
}
